### ISSUE TITLE
missing foregroundservicetype

### ISSUE THREAD

**Issue by ishwor-khadka** [CodeInKotLang/StudySmart#2]
Android manifest xml requires foregroundServiceType to startforeground  which is missing in your code.

**Comment by ishwor-khadka** [comment]
used foregroundtype = shortService which working perfectly. #solved

**Comment by brijeshwargt** [comment]
> Android manifest xml requires foregroundServiceType to startforeground which is missing in your code.

can you tell where we exactly need to add this ? with what syntax
